#!/bin/bash
# flash_fpga.sh
# Automates flashing the Cyclone IV via the USB-Blaster in WSL2

# The path to the bitstream generated by your 'make synth' command
SOF_FILE="build/output_files/top_motor_controller.sof"

echo "========================================"
echo " Starting Automated FPGA Flashing..."
echo " Target: $SOF_FILE"
echo "========================================"

# 1. Verify the bitstream exists
if [ ! -f "$SOF_FILE" ]; then
    echo "ERROR: .sof file not found at $SOF_FILE."
    echo "Did you run 'make synth' first?"
    exit 1
fi

# 2. Check if quartus_pgm is in the system PATH
if ! command -v quartus_pgm &> /dev/null; then
    echo "ERROR: quartus_pgm could not be found."
    echo "Please ensure the Quartus bin directory is added to your ~/.bashrc PATH."
    exit 1
fi

# 3. Execute the flash command over JTAG
# -c "USB-Blaster" tells it which cable to use
# -m jtag sets the programming mode
# -o "p;..." tells it to program (p) the specified file
echo "Connecting to USB-Blaster..."
quartus_pgm -c "USB-Blaster" -m jtag -o "p;${SOF_FILE}"

# 4. Capture the exit status
if [ $? -eq 0 ]; then
    echo "========================================"
    echo " SUCCESS: FPGA Flashed Successfully!"
    echo "========================================"
    exit 0
else
    echo "========================================"
    echo " ERROR: Flashing failed."
    echo " Check your USB passthrough and board power."
    echo "========================================"
    exit 1
fi